In [1]:
import numpy as np

In [2]:
X_test=np.array([[1,2,3],[2,3,4]])

In [3]:
X_test

array([[1, 2, 3],
       [2, 3, 4]])

In [10]:
next_prediction=[[2]]

In [11]:
np.vstack([X_test[0,1:], next_prediction])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

In [12]:
import numpy as np

# Example NumPy array with strings
string_array = np.array(['1.2', '3.4', '5.6', '7.8'])

# Convert strings to float
float_array = string_array.astype(float)

# Print the result
print(float_array)

[1.2 3.4 5.6 7.8]


In [22]:
x=[[1,2,3]]
y=[[2,3,4]]
np.concatenate((np.array(x)[:,2:],y),1)


array([[3, 2, 3, 4]])

In [17]:
np.array(x).shape

(1, 3)

In [25]:
x=np.array([[[1,2],[2,3]],[[1,2],[2,3]]])

In [30]:
x=np.array([1,2,3,4,5,6])
x.reshape(2,-1).reshape(1,-1)

array([[1, 2, 3, 4, 5, 6]])

In [31]:
x=[[1,2,3]]
y=[[2,3,4]]
np.concatenate(np.array(x)[:,2:],y)

TypeError: 'list' object cannot be interpreted as an integer

In [32]:
x=np.array([1,2,3,4,5,6])
x=x.reshape(3,2)

In [33]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
x.reshape(1,3,2)

array([[[1, 2],
        [3, 4],
        [5, 6]]])